runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30s"

instance_class: F2

skip_files:
- ^(?!dist).*$  # Skip any files not in the dist folder

handlers:
  - url: "/((?:inline|main|polyfills|styles|vendor|runtime|scripts)\\.[a-z0-9]+\\.js)"
    static_files: "dist/\\1"
    require_matching_file: false
    application_readable: false
    upload: 'dist/.*'
  - url: "/(styles\\.[a-z0-9]+\\.css)"
    static_files: "dist/\\1"
    require_matching_file: false
    application_readable: false
    upload: 'dist/.*'
  - url: "/((?:assets|docs)/.*|favicon\\.ico)"
    static_files: "dist/\\1"
    require_matching_file: false
    application_readable: false
    upload: 'dist/.*'
  - url: "/((?:color|background|hue|line|loading|password-meter)\\.[a-z0-9]+\\.(?:jpg|png|svg|gif))"
    static_files: "dist/\\1"
    require_matching_file: false
    application_readable: false
    upload: 'dist/.*'
  - url: "/((?:fontawesome-webfont|open-sans-v15-latin-regular|open-sans-v15-latin-700|open-sans-v15-latin-300|primeicons)\\.[a-z0-9]+\\.(?:svg|eot|woff2|ttf|woff))"
    static_files: "dist/\\1"
    require_matching_file: false
    application_readable: false
    upload: 'dist/.*'
  - url: "/3rdpartylicenses.txt"
    static_files: "dist/3rdpartylicenses.txt"
    require_matching_file: false
    application_readable: false
    upload: 'dist/3rdpartylicenses.txt'
  - url: '/.*'
    static_files: dist/index.html
    require_matching_file: false
    upload: "dist/index.html"